### ISSUE TITLE
Bug in DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5

### ISSUE THREAD

**Issue by proan** [ZettaScaleLabs/roscon2024_workshop#12]
I have added in rmw_zenoh to my Turtlebot2 docker container (git clone and build source). I'm attempting to follow Example 2, but the DEFAULT_RMW_ZENOH_ROUTER_CONFIG.json5 file has an error in it. When I try to run `ZENOH_ROUTER_CONFIG_URI=/ros_ws/zenoh_confs/ROUTER_CONFIG.json5 ros2 run rmw_zenoh_cpp rmw_zenohd`

I get
```
logging system isn't initialized: call to rcutils_logging_console_output_handler failed.
[ros2run]: Process exited with failure 1
```
which indicates an error in the config file.

I was working through this example earlier in the week without issues, so I expect a recent merge inserted an error somewhere.

**Comment by proan** [comment]
If I use the default from https://github.com/ZettaScaleLabs/roscon2024_workshop/commit/1df70614eaee4908d0be2f1aa8a1d0d27d6d270f, then I do not receive the error and the router launches as expected.

**Comment by proan** [comment]
I am using the official [ROS 2 rmw_zenoh repo](https://github.com/ros2/rmw_zenoh.git), and it could be that Zetta Scale has updated their fork resolving this bug. If this is the case, it is not clear that this config file is not compatible with the official sources.

**Comment by imstevenpmwork** [comment]
> I am using the official [ROS 2 rmw_zenoh repo](https://github.com/ros2/rmw_zenoh.git), and it could be that Zetta Scale has updated their fork resolving this bug. If this is the case, it is not clear that this config file is not compatible with the official sources.

In this repository, we point to our fork instead of the official repository. The recent merges set a version of `rmw_zenoh` that uses Zenoh `v1.0.0`, which introduced configuration changes. This was done to accommodate recent workshops. Until recently, the `rolling` branch of `rmw_zenoh` in the official ROS 2 repository was based on Zenoh `v0.11.0`. As a result, the current configuration file from this repository is incompatible with that version.

However, the official repository has now transitioned its `rmw_zenoh` implementation to Zenoh `v1.0.0`. This update has been merged into the `rolling` branch. This means that if you try using the `rolling` branch again, it should now work as expected with these configurations.

That being said, since `dev/1.0.0` has been merged into `rolling`, I will likely update this repository to point to the `rmw_zenoh` repository in the official sources. This however, shouldn't affect the configuration files.
